# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/run_vivado/mycpu_prj1/mycpu.cache/wt [current_project]
set_property parent.project_path D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/run_vivado/mycpu_prj1/mycpu.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
add_files D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/soft/func_lab9/obj/inst_ram.coe
read_verilog -library xil_defaultlib {
  D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/rtl/BRIDGE/bridge_1x2.v
  D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/rtl/CONFREG/confreg.v
  D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/cpu132_gettrace/rtl/CPU_gs132/ls132r_decode_stage.v
  D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/cpu132_gettrace/rtl/CPU_gs132/ls132r_ejtag_dcr.v
  D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/cpu132_gettrace/rtl/CPU_gs132/ls132r_ejtag_hb.v
  D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/cpu132_gettrace/rtl/CPU_gs132/ls132r_ejtag_tap.v
  D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/cpu132_gettrace/rtl/CPU_gs132/ls132r_ejtag_tap_buffer.v
  D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/cpu132_gettrace/rtl/CPU_gs132/ls132r_execute_stage.v
  D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/cpu132_gettrace/rtl/CPU_gs132/ls132r_fetch_stage.v
  D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/cpu132_gettrace/rtl/CPU_gs132/ls132r_interface.v
  D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/cpu132_gettrace/rtl/CPU_gs132/ls132r_tools.v
  D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/cpu132_gettrace/rtl/CPU_gs132/ls132r_top.v
  D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/rtl/myCPU/mycpu_top.v
  D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/rtl/ram_wrap/sram_wrap.v
  D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/rtl/soc_sram_lite_top.v
}
read_ip -quiet D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all d:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/rtl/xilinx_ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all d:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/rtl/xilinx_ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all d:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/rtl/xilinx_ip/clk_pll/clk_pll_ooc.xdc]

read_ip -quiet D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/rtl/xilinx_ip/data_ram/data_ram.xci
set_property used_in_implementation false [get_files -all d:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc]

read_ip -quiet D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/rtl/xilinx_ip/inst_ram/inst_ram.xci
set_property used_in_implementation false [get_files -all d:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/rtl/xilinx_ip/inst_ram/inst_ram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/run_vivado/soc_lite.xdc
set_property used_in_implementation false [get_files D:/pipline_better/lab4/lab10/CPU_CDE_SRAM/mycpu_sram_verify/run_vivado/soc_lite.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_sram_lite_top -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_sram_lite_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_sram_lite_top_utilization_synth.rpt -pb soc_sram_lite_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
