# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/pipline_better/lab4/lab11/CPU_CDE_AXI/mycpu_axi_verify/run_vivado/mycpu_prj1/cpu_tlb_cache/cpu_tlb_cache.cache/wt [current_project]
set_property parent.project_path D:/pipline_better/lab4/lab11/CPU_CDE_AXI/mycpu_axi_verify/run_vivado/mycpu_prj1/cpu_tlb_cache/cpu_tlb_cache.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/pipline_better/lab4/lab11/CPU_CDE_AXI/mycpu_axi_verify/run_vivado/mycpu_prj1/cpu_tlb_cache/cpu_tlb_cache.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/pipline_better/lab5/labcode/mycpu/inst_pipeline.coe
read_verilog D:/pipline_better/lab5/labcode/mycpu/exception_defines.vh
read_mem D:/pipline_better/lab5/labcode/mycpu/inst_rom.mif
read_verilog -library xil_defaultlib {
  D:/pipline_better/lab5/labcode/mycpu/adder.v
  D:/pipline_better/lab5/labcode/mycpu/alu.v
  D:/pipline_better/lab5/labcode/lab16/cache_verify/rtl/cache/cache.v
  D:/pipline_better/lab5/labcode/mycpu/decode.v
  D:/pipline_better/lab5/labcode/mycpu/exe.v
  D:/pipline_better/lab5/labcode/mycpu/fetch.v
  D:/pipline_better/lab5/labcode/mycpu/mem.v
  D:/pipline_better/lab5/labcode/mycpu/multiply.v
  D:/pipline_better/lab5/labcode/mycpu/regfile.v
  D:/pipline_better/lab5/labcode/lab13/tlb_verify/rtl/tlb/tlb.v
  D:/pipline_better/lab5/labcode/mycpu/wb.v
  D:/pipline_better/lab5/labcode/mycpu/cpu_with_tlb_cache.v
}
read_ip -quiet D:/pipline_better/lab4/lab11/CPU_CDE_AXI/mycpu_axi_verify/run_vivado/mycpu_prj1/cpu_tlb_cache/cpu_tlb_cache.srcs/sources_1/ip/data_ram/data_ram.xci
set_property used_in_implementation false [get_files -all d:/pipline_better/lab4/lab11/CPU_CDE_AXI/mycpu_axi_verify/run_vivado/mycpu_prj1/cpu_tlb_cache/cpu_tlb_cache.srcs/sources_1/ip/data_ram/data_ram_ooc.xdc]

read_ip -quiet D:/pipline_better/lab4/lab11/CPU_CDE_AXI/mycpu_axi_verify/run_vivado/mycpu_prj1/cpu_tlb_cache/cpu_tlb_cache.srcs/sources_1/ip/inst_rom/inst_rom.xci
set_property used_in_implementation false [get_files -all d:/pipline_better/lab4/lab11/CPU_CDE_AXI/mycpu_axi_verify/run_vivado/mycpu_prj1/cpu_tlb_cache/cpu_tlb_cache.srcs/sources_1/ip/inst_rom/inst_rom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cpu_with_tlb_cache -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cpu_with_tlb_cache.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cpu_with_tlb_cache_utilization_synth.rpt -pb cpu_with_tlb_cache_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
